version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-vol-1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}

  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - 3306:3306
    container_name: python_app
    volumes:
      - python-vol-1:/var/app
    restart: always

volumes:
  mysql-vol-1:
  python-vol-1:

