apiVersion: v1 # kubernetes 버전
kind: Service # 종류는 서비스
metadata:   # 메타데이터 설정
  name: np-svc  # 이름을 np-svc라고 한다
spec: # 서비스의 스펙 설정
  selector:
    app: np-pods  # app 레이블이 np-podes로 설정된 모든 파드가 대상
  ports:  # 포트 설정
    -name: http  # 이름은 http
    protocol: TCP   # 프로토콜은 TCP
    port: 80 # 이 서비스의 포트 번호 
    targetPort: 80 # 이 서브사가 트래픽을 보낼 대상 파드의 포트 번호
    nodePort: 30000 # 클러스터 외부에서 이 서비스에 접근할 때 사용하는 포트 번호. 모든 클러스터 노드에서 이 포트가 열려 있을 것임.
type: nodePort # 서비스의 타입. NodePort는 클러스터의 각 노드에 고정 포트를 할당하고, 해당 포트로 들어오는 트래픽을 서비스로 라우팅함.

# 이 서비스는 레이블이 'app:np-pods'인 파드에 대한 접근을 관리하고, 클러스터 외부에서는 NodePort(30000번 포트)를 통해 이 서비스에 접근할 수 있음.