version: "3"

services:
  db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile-mysql
    volumes:
      - mysql-vol-1:/var/lib/mysql
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    container_name: mysql-vol-1

  app:
    build:
      context: .
      dockerfile: ./Dockerfile-python
    depends_on:
      - db
    network_mode: host
    container_name: python_app
    restart: always

volumes:
  mysql-vol-1:
  python-vol-1:

